export const NOTIFICATION_MODULE_KEYS = {
  DOC_RECEIVING: "DOC_RECEIVING",
  HATCHERY_DOC_DISPATCH: "HATCHERY_DOC_DISPATCH",
  ITEM_GROUP: "ITEM_GROUP",
} as const

export const NOTIFICATION_EVENT_KEYS = {
  DOC_RECEIVING: {
    POSTED: "DOC_RECEIVING_POSTED",
  },
  HATCHERY_DOC_DISPATCH: {
    POSTED: "HATCHERY_DOC_DISPATCH_POSTED",
  },
  ITEM_GROUP: {
    EDITED: "ITEM_GROUP_EDITED",
    VOIDED: "ITEM_GROUP_VOIDED",
  },
} as const
