export const NOTIFICATION_MODULE_KEYS = {
  DOC_RECEIVING: "DOC_RECEIVING",
  HATCHERY_DOC_DISPATCH: "HATCHERY_DOC_DISPATCH",
  ITEM_GROUP: "ITEM_GROUP",
  ITEM_MASTER: "ITEM_MASTER",
  WORKSPACE_PROJECT: "WORKSPACE_PROJECT",
  WORKSPACE_TASK: "WORKSPACE_TASK",
  WORKSPACE_TIMESHEET: "WORKSPACE_TIMESHEET",
} as const

export const NOTIFICATION_EVENT_KEYS = {
  DOC_RECEIVING: {
    POSTED: "DOC_RECEIVING_POSTED",
  },
  HATCHERY_DOC_DISPATCH: {
    POSTED: "HATCHERY_DOC_DISPATCH_POSTED",
  },
  ITEM_GROUP: {
    EDITED: "ITEM_GROUP_EDITED",
    VOIDED: "ITEM_GROUP_VOIDED",
  },
  ITEM_MASTER: {
    EDITED: "ITEM_MASTER_EDITED",
  },
  WORKSPACE_PROJECT: {
    POSTED: "WORKSPACE_PROJECT_POSTED",
    EDITED: "WORKSPACE_PROJECT_EDITED",
    VOIDED: "WORKSPACE_PROJECT_VOIDED",
  },
  WORKSPACE_TASK: {
    POSTED: "WORKSPACE_TASK_POSTED",
    EDITED: "WORKSPACE_TASK_EDITED",
    VOIDED: "WORKSPACE_TASK_VOIDED",
  },
  WORKSPACE_TIMESHEET: {
    POSTED: "WORKSPACE_TIMESHEET_POSTED",
    EDITED: "WORKSPACE_TIMESHEET_EDITED",
  },
} as const
