-- Vitarich notification rules, transactional outbox, inbox and email
-- deliveries, and DOC Placement and Hatchery DOC Dispatch integrations.
-- Apply this script to Supabase before enabling /admin/notifications.

create table if not exists public.notification_rules (
  id bigint generated by default as identity primary key,
  name text not null,
  module_key text not null,
  event_key text not null,
  fms_types text[] not null default '{}'::text[],
  source_fms_types text[] not null default '{}'::text[],
  recipient_fms_types text[] not null default '{}'::text[],
  user_types smallint[] not null default '{}'::smallint[],
  user_group_ids bigint[] not null default '{}'::bigint[],
  title_template text null,
  message_template text null,
  priority text not null default 'normal',
  exclude_actor boolean not null default true,
  require_view_permission boolean not null default true,
  is_active boolean not null default true,
  void text not null default '1',
  created_by uuid null references auth.users(id),
  created_at timestamp with time zone not null default now(),
  updated_by uuid null references auth.users(id),
  updated_at timestamp with time zone null,
  constraint notification_rules_name_check check (length(btrim(name)) > 0),
  constraint notification_rules_module_key_check check (module_key ~ '^[A-Z0-9_]+$'),
  constraint notification_rules_event_key_check check (event_key ~ '^[A-Z0-9_]+$'),
  constraint notification_rules_fms_types_check check (
    fms_types <@ array['Broiler', 'Breeder', 'Hatchery']::text[]
  ),
  constraint notification_rules_source_fms_types_check check (
    source_fms_types <@ array['Broiler', 'Breeder', 'Hatchery']::text[]
  ),
  constraint notification_rules_recipient_fms_types_check check (
    recipient_fms_types <@ array['Broiler', 'Breeder', 'Hatchery']::text[]
  ),
  constraint notification_rules_user_types_check check (
    user_types <@ array[1, 2, 3]::smallint[]
  ),
  constraint notification_rules_priority_check check (
    priority in ('low', 'normal', 'high', 'critical')
  ),
  constraint notification_rules_void_check check (void in ('0', '1'))
);

alter table public.notification_rules
  add column if not exists source_fms_types text[] not null default '{}'::text[];

alter table public.notification_rules
  add column if not exists recipient_fms_types text[] not null default '{}'::text[];

alter table public.notification_rules
  add column if not exists email_enabled boolean not null default false;

-- Preserve existing same-FMS rules while separating the trigger FMS from the
-- recipient FMS for new cross-FMS rules.
update public.notification_rules
set source_fms_types = fms_types
where cardinality(source_fms_types) = 0 and cardinality(fms_types) > 0;

update public.notification_rules
set recipient_fms_types = fms_types
where cardinality(recipient_fms_types) = 0 and cardinality(fms_types) > 0;

create index if not exists notification_rules_event_idx
  on public.notification_rules (module_key, event_key, is_active)
  where void = '1';

create table if not exists public.notification_outbox (
  id uuid primary key default gen_random_uuid(),
  module_key text not null,
  event_key text not null,
  entity_type text not null,
  entity_id text not null,
  document_no text null,
  fms_type text null,
  farm_id bigint null,
  recipient_farm_id bigint null references public.farms(id),
  actor_auth_id uuid null references auth.users(id),
  target_url text null,
  permission_group text not null,
  permission_title text not null,
  title text not null,
  message text not null,
  priority text not null default 'normal',
  posting_version integer null,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text not null,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  last_error text null,
  next_attempt_at timestamp with time zone not null default now(),
  occurred_at timestamp with time zone not null default now(),
  processing_started_at timestamp with time zone null,
  processed_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint notification_outbox_dedupe_key_key unique (dedupe_key),
  constraint notification_outbox_module_key_check check (module_key ~ '^[A-Z0-9_]+$'),
  constraint notification_outbox_event_key_check check (event_key ~ '^[A-Z0-9_]+$'),
  constraint notification_outbox_fms_type_check check (
    fms_type is null or fms_type in ('Broiler', 'Breeder', 'Hatchery')
  ),
  constraint notification_outbox_priority_check check (
    priority in ('low', 'normal', 'high', 'critical')
  ),
  constraint notification_outbox_status_check check (
    status in ('pending', 'processing', 'processed', 'failed', 'skipped', 'invalid')
  ),
  constraint notification_outbox_attempt_count_check check (attempt_count >= 0),
  constraint notification_outbox_metadata_check check (jsonb_typeof(metadata) = 'object')
);

alter table public.notification_outbox
  add column if not exists recipient_farm_id bigint null references public.farms(id);

create index if not exists notification_outbox_processing_idx
  on public.notification_outbox (status, next_attempt_at, occurred_at)
  where status in ('pending', 'failed');

create index if not exists notification_outbox_source_idx
  on public.notification_outbox (entity_type, entity_id, occurred_at desc);

create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.notification_outbox(id) on delete cascade,
  rule_id bigint null references public.notification_rules(id) on delete set null,
  recipient_user_id bigint not null references public.users(id) on delete cascade,
  recipient_auth_id uuid not null references auth.users(id) on delete cascade,
  module_key text not null,
  event_key text not null,
  title text not null,
  message text not null,
  priority text not null default 'normal',
  target_url text null,
  occurred_at timestamp with time zone not null,
  delivered_at timestamp with time zone not null default now(),
  seen_at timestamp with time zone null,
  read_at timestamp with time zone null,
  archived_at timestamp with time zone null,
  constraint user_notifications_event_recipient_key unique (event_id, recipient_auth_id),
  constraint user_notifications_priority_check check (
    priority in ('low', 'normal', 'high', 'critical')
  )
);

create index if not exists user_notifications_recipient_idx
  on public.user_notifications (recipient_auth_id, occurred_at desc);

create index if not exists user_notifications_unread_idx
  on public.user_notifications (recipient_auth_id, occurred_at desc)
  where read_at is null and archived_at is null;

create table if not exists public.notification_email_deliveries (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.notification_outbox(id) on delete cascade,
  rule_id bigint null references public.notification_rules(id) on delete set null,
  user_notification_id bigint null references public.user_notifications(id) on delete set null,
  recipient_user_id bigint not null references public.users(id) on delete cascade,
  recipient_auth_id uuid not null references auth.users(id) on delete cascade,
  recipient_email text null,
  recipient_name text null,
  recipient_fms_type text null,
  initiator_name text null,
  module_key text not null,
  event_key text not null,
  document_no text null,
  title text not null,
  message text not null,
  priority text not null default 'normal',
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamp with time zone not null,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  last_error text null,
  next_attempt_at timestamp with time zone not null default now(),
  processing_started_at timestamp with time zone null,
  sent_at timestamp with time zone null,
  provider_message_id text null,
  created_at timestamp with time zone not null default now(),
  constraint notification_email_event_recipient_key unique (event_id, recipient_auth_id),
  constraint notification_email_fms_type_check check (
    recipient_fms_type is null or recipient_fms_type in ('Broiler', 'Breeder', 'Hatchery')
  ),
  constraint notification_email_priority_check check (
    priority in ('low', 'normal', 'high', 'critical')
  ),
  constraint notification_email_status_check check (
    status in ('pending', 'processing', 'sent', 'failed', 'skipped')
  ),
  constraint notification_email_attempt_count_check check (attempt_count >= 0),
  constraint notification_email_metadata_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists notification_email_processing_idx
  on public.notification_email_deliveries (status, next_attempt_at, occurred_at)
  where status in ('pending', 'failed');

alter table public.notification_rules enable row level security;
alter table public.notification_outbox enable row level security;
alter table public.user_notifications enable row level security;
alter table public.notification_email_deliveries enable row level security;

drop policy if exists user_notifications_select_own on public.user_notifications;
create policy user_notifications_select_own
  on public.user_notifications
  for select
  to authenticated
  using (recipient_auth_id = auth.uid());

drop policy if exists user_notifications_update_own on public.user_notifications;

-- Realtime needs SELECT, while read-state changes remain behind the secured
-- API so clients cannot alter event, recipient, title, or routing fields.
grant select on public.user_notifications to authenticated;

alter table public.user_notifications replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'user_notifications'
  ) then
    alter publication supabase_realtime add table public.user_notifications;
  end if;
end;
$$;

create or replace function public.set_notification_rule_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists notification_rules_set_updated_at on public.notification_rules;
create trigger notification_rules_set_updated_at
before update on public.notification_rules
for each row execute function public.set_notification_rule_updated_at();

-- Source verification in the dispatcher and the source-table triggers both
-- depend on these posting identity columns.
alter table public.goods_receipt
  add column if not exists posted_at timestamp with time zone null;

alter table public.goods_receipt
  add column if not exists posted_by uuid null references auth.users(id);

alter table public.goods_receipt
  add column if not exists posting_version integer not null default 0;

alter table public.dispatch_doc
  add column if not exists destination_farm_id bigint null references public.farms(id);

alter table public.dispatch_doc
  add column if not exists destination_farm_code text null;

alter table public.dispatch_doc
  add column if not exists status text not null default 'Draft';

alter table public.dispatch_doc
  add column if not exists posted_at timestamp with time zone null;

alter table public.dispatch_doc
  add column if not exists posted_by uuid null references auth.users(id);

alter table public.dispatch_doc
  add column if not exists posting_version integer not null default 0;

-- Backfill a resolvable document farm onto previously queued DOC Placement
-- events when this migration is reapplied. Unresolvable legacy events remain
-- unchanged and will be marked Invalid by the dispatcher instead of becoming
-- unrestricted deliveries.
update public.notification_outbox event_row
set farm_id = receipt.farm_id,
    recipient_farm_id = receipt.farm_id
from public.goods_receipt receipt
where event_row.module_key = 'DOC_RECEIVING'
  and event_row.event_key = 'DOC_RECEIVING_POSTED'
  and event_row.entity_id ~ '^[0-9]+$'
  and receipt.id = event_row.entity_id::bigint
  and receipt.farm_id is not null
  and exists (select 1 from public.farms farm where farm.id = receipt.farm_id)
  and (event_row.farm_id is distinct from receipt.farm_id
       or event_row.recipient_farm_id is distinct from receipt.farm_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.dispatch_doc'::regclass
      and conname = 'dispatch_doc_status_check'
  ) then
    alter table public.dispatch_doc
      add constraint dispatch_doc_status_check check (status in ('Draft', 'Posted'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.notification_rules'::regclass
      and conname = 'notification_rules_source_fms_types_check'
  ) then
    alter table public.notification_rules
      add constraint notification_rules_source_fms_types_check
      check (source_fms_types <@ array['Broiler', 'Breeder', 'Hatchery']::text[]);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.notification_rules'::regclass
      and conname = 'notification_rules_recipient_fms_types_check'
  ) then
    alter table public.notification_rules
      add constraint notification_rules_recipient_fms_types_check
      check (recipient_fms_types <@ array['Broiler', 'Breeder', 'Hatchery']::text[]);
  end if;
end;
$$;

create or replace function public.process_notification_outbox(p_limit integer default 50)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.notification_outbox%rowtype;
  v_processed integer := 0;
  v_next_attempt timestamp with time zone;
  v_source_valid boolean;
begin
  for v_event in
    select event_row.*
    from public.notification_outbox event_row
    where event_row.status in ('pending', 'failed')
      and event_row.next_attempt_at <= now()
    order by event_row.occurred_at, event_row.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 50), 200))
  loop
    begin
      update public.notification_outbox
      set status = 'processing',
          processing_started_at = now(),
          last_error = null
      where id = v_event.id;

      -- Each module integration must provide an authoritative verifier. The
      -- first integration accepts only the same DOC Placement posting version
      -- that was atomically stamped by the source-table trigger.
      if v_event.module_key = 'DOC_RECEIVING' and v_event.event_key = 'DOC_RECEIVING_POSTED' then
        if v_event.entity_id !~ '^[0-9]+$' then
          update public.notification_outbox
          set status = 'invalid',
              processed_at = now(),
              processing_started_at = null,
              last_error = 'DOC Placement source ID is invalid.'
          where id = v_event.id;
          continue;
        end if;

        if v_event.recipient_farm_id is null then
          update public.notification_outbox
          set status = 'invalid',
              processed_at = now(),
              processing_started_at = null,
              last_error = 'DOC Placement document farm is missing.'
          where id = v_event.id;
          continue;
        end if;

        select exists (
          select 1
          from public.goods_receipt receipt
          join public.farms farm on farm.id = receipt.farm_id
          where receipt.id = v_event.entity_id::bigint
            and lower(btrim(coalesce(receipt.status, ''))) in ('posted', 'received')
            and receipt.posting_version = v_event.posting_version
            and receipt.farm_id = v_event.farm_id
            and receipt.farm_id = v_event.recipient_farm_id
        ) into v_source_valid;

        if not coalesce(v_source_valid, false) then
          update public.notification_outbox
          set status = 'invalid',
              processed_at = now(),
              processing_started_at = null,
              last_error = 'DOC Placement is not posted at the recorded posting version.'
          where id = v_event.id;
          continue;
        end if;
      elsif v_event.module_key = 'HATCHERY_DOC_DISPATCH'
            and v_event.event_key = 'HATCHERY_DOC_DISPATCH_POSTED' then
        if v_event.entity_id !~ '^[0-9]+$' then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Hatchery DOC Dispatch source ID is invalid.'
          where id = v_event.id;
          continue;
        end if;

        if v_event.recipient_farm_id is null then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Hatchery DOC Dispatch destination farm is missing.'
          where id = v_event.id;
          continue;
        end if;

        select exists (
          select 1
          from public.dispatch_doc dispatch
          where dispatch.id = v_event.entity_id::bigint
            and dispatch.status = 'Posted'
            and dispatch.is_active
            and dispatch.posting_version = v_event.posting_version
            and dispatch.destination_farm_id = v_event.farm_id
            and dispatch.destination_farm_id = v_event.recipient_farm_id
        ) into v_source_valid;

        if not coalesce(v_source_valid, false) then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Hatchery DOC Dispatch is not posted at the recorded posting version.'
          where id = v_event.id;
          continue;
        end if;
      elsif v_event.module_key = 'VACCINATION_MEDS'
            and v_event.event_key in ('VACCINATION_MEDS_POSTED', 'VACCINATION_MEDS_EDITED', 'VACCINATION_MEDS_VOIDED') then
        if v_event.entity_id !~ '^[0-9]+$' then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Vaccination and Meds source ID is invalid.'
          where id = v_event.id;
          continue;
        end if;

        if v_event.farm_id is null or v_event.recipient_farm_id is null then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Vaccination and Meds document farm is missing.'
          where id = v_event.id;
          continue;
        end if;

        select exists (
          select 1
          from public.vnm_documents document
          join public.farms farm on farm.id = document.farm_id
          where document.id = v_event.entity_id::bigint
            and document.farm_id = v_event.farm_id
            and document.farm_id = v_event.recipient_farm_id
            and document.fms_type = v_event.fms_type
            and (
              (v_event.event_key = 'VACCINATION_MEDS_EDITED'
                and coalesce((v_event.metadata ->> 'editVersion')::integer, -1) between 1 and document.edit_version)
              or (v_event.event_key = 'VACCINATION_MEDS_POSTED'
                and document.status in ('Posted', 'Void')
                and document.posted_at is not null
                and document.posting_version = v_event.posting_version)
              or (v_event.event_key = 'VACCINATION_MEDS_VOIDED'
                and document.status = 'Void'
                and document.voided_at is not null
                and document.posting_version = v_event.posting_version)
            )
        ) into v_source_valid;

        if not coalesce(v_source_valid, false) then
          update public.notification_outbox
          set status = 'invalid', processed_at = now(), processing_started_at = null,
              last_error = 'Vaccination and Meds source does not match the recorded event version and farm.'
          where id = v_event.id;
          continue;
        end if;
      end if;

      with initiator_profile as (
        select concat_ws(' ', nullif(btrim(firstname), ''), nullif(btrim(lastname), '')) as initiator_name
        from public.users
        where auth_id = v_event.actor_auth_id
        limit 1
      ),
      ranked_recipients as (
        select distinct on (recipient.auth_id)
          rule.id as rule_id,
          recipient.id as recipient_user_id,
          recipient.auth_id as recipient_auth_id,
          rule.priority,
          replace(replace(
            replace(
              coalesce(nullif(btrim(rule.title_template), ''), v_event.title),
              '{document_no}', coalesce(v_event.document_no, '')
            ),
            '{initiator_name}', coalesce(nullif((select initiator_name from initiator_profile), ''), 'a user')
          ),
            '{actor_name}', coalesce(nullif((select initiator_name from initiator_profile), ''), 'a user')
          ) as rendered_title,
          replace(replace(
            replace(
              coalesce(nullif(btrim(rule.message_template), ''), v_event.message),
              '{document_no}', coalesce(v_event.document_no, '')
            ),
            '{initiator_name}', coalesce(nullif((select initiator_name from initiator_profile), ''), 'a user')
          ),
            '{actor_name}', coalesce(nullif((select initiator_name from initiator_profile), ''), 'a user')
          ) as rendered_message
        from public.notification_rules rule
        join public.users recipient on recipient.auth_id is not null
        where rule.void = '1'
          and rule.is_active
          and rule.module_key = v_event.module_key
          and rule.event_key = v_event.event_key
          and (
            cardinality(rule.source_fms_types) = 0
            or v_event.fms_type = any(rule.source_fms_types)
          )
          and (
            coalesce(recipient.user_type, 3) = 1
            or cardinality(rule.recipient_fms_types) = 0
            or recipient.fms_type = any(rule.recipient_fms_types)
          )
          and (
            cardinality(rule.user_types) = 0
            or coalesce(recipient.user_type, 3)::smallint = any(rule.user_types)
          )
          and (
            cardinality(rule.user_group_ids) = 0
            or recipient.users_group_id = any(rule.user_group_ids)
          )
          and btrim(coalesce(recipient.isactive::text, '0')) = '1'
          and (
            coalesce(recipient.user_type, 3) = 1
            or v_event.recipient_farm_id is null
            or exists (
              select 1
              from public.users_farms recipient_farm
              left join public.farms farm on farm.code = recipient_farm.farm_code
              where recipient_farm.users_id = recipient.id
                and btrim(coalesce(recipient_farm.void::text, '0')) = '1'
                and coalesce(recipient_farm.farm_id, farm.id) = v_event.recipient_farm_id
            )
          )
          and (
            not rule.exclude_actor
            or recipient.auth_id is distinct from v_event.actor_auth_id
          )
          and (
            not rule.require_view_permission
            or coalesce(recipient.user_type, 3) = 1
            or exists (
              select 1
              from public.user_permissions permission
              where permission.user_id = recipient.auth_id
                and permission.group_name = v_event.permission_group
                and permission.title = v_event.permission_title
                and permission.is_visible
            )
          )
        order by
          recipient.auth_id,
          case rule.priority
            when 'critical' then 1
            when 'high' then 2
            when 'normal' then 3
            else 4
          end,
          rule.id
      )
      insert into public.user_notifications (
        event_id,
        rule_id,
        recipient_user_id,
        recipient_auth_id,
        module_key,
        event_key,
        title,
        message,
        priority,
        target_url,
        occurred_at
      )
      select
        v_event.id,
        recipient.rule_id,
        recipient.recipient_user_id,
        recipient.recipient_auth_id,
        v_event.module_key,
        v_event.event_key,
        recipient.rendered_title,
        recipient.rendered_message,
        recipient.priority,
        v_event.target_url,
        v_event.occurred_at
      from ranked_recipients recipient
      on conflict (event_id, recipient_auth_id) do nothing;

      insert into public.notification_email_deliveries (
        event_id,
        rule_id,
        user_notification_id,
        recipient_user_id,
        recipient_auth_id,
        recipient_email,
        recipient_name,
        recipient_fms_type,
        initiator_name,
        module_key,
        event_key,
        document_no,
        title,
        message,
        priority,
        metadata,
        occurred_at,
        status,
        last_error
      )
      select
        inbox.event_id,
        inbox.rule_id,
        inbox.id,
        inbox.recipient_user_id,
        inbox.recipient_auth_id,
        nullif(btrim(recipient.email), ''),
        coalesce(
          nullif(concat_ws(' ', nullif(btrim(recipient.firstname), ''), nullif(btrim(recipient.lastname), '')), ''),
          nullif(btrim(recipient.email), ''),
          'FMS user'
        ),
        case
          when recipient.fms_type in ('Broiler', 'Breeder', 'Hatchery') then recipient.fms_type
          when cardinality(rule.recipient_fms_types) = 1 then rule.recipient_fms_types[1]
          else v_event.fms_type
        end,
        coalesce(
          nullif((
            select concat_ws(' ', nullif(btrim(initiator.firstname), ''), nullif(btrim(initiator.lastname), ''))
            from public.users initiator
            where initiator.auth_id = v_event.actor_auth_id
            limit 1
          ), ''),
          'a user'
        ),
        inbox.module_key,
        inbox.event_key,
        v_event.document_no,
        inbox.title,
        inbox.message,
        inbox.priority,
        v_event.metadata,
        inbox.occurred_at,
        case
          when btrim(coalesce(recipient.email, '')) ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then 'pending'
          else 'skipped'
        end,
        case
          when btrim(coalesce(recipient.email, '')) ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then null
          else 'Recipient user profile has no valid email address.'
        end
      from public.user_notifications inbox
      join public.notification_rules rule on rule.id = inbox.rule_id and rule.email_enabled
      join public.users recipient on recipient.id = inbox.recipient_user_id
      where inbox.event_id = v_event.id
      on conflict (event_id, recipient_auth_id) do nothing;

      update public.notification_outbox
      set status = 'processed',
          processed_at = now(),
          processing_started_at = null,
          last_error = null
      where id = v_event.id;

      v_processed := v_processed + 1;
    exception when others then
      v_next_attempt := now() + case
        when v_event.attempt_count <= 0 then interval '1 minute'
        when v_event.attempt_count = 1 then interval '5 minutes'
        when v_event.attempt_count = 2 then interval '15 minutes'
        else interval '1 hour'
      end;

      update public.notification_outbox
      set status = 'failed',
          attempt_count = attempt_count + 1,
          last_error = sqlerrm,
          next_attempt_at = v_next_attempt,
          processing_started_at = null
      where id = v_event.id;
    end;
  end loop;

  return v_processed;
end;
$$;

revoke all on function public.process_notification_outbox(integer) from public;
revoke all on function public.process_notification_outbox(integer) from anon;
revoke all on function public.process_notification_outbox(integer) from authenticated;
grant execute on function public.process_notification_outbox(integer) to service_role;

create or replace function public.claim_notification_email_deliveries(p_limit integer default 20)
returns setof public.notification_email_deliveries
language sql
security definer
set search_path = public
as $$
  with claimed as (
    select delivery.id
    from public.notification_email_deliveries delivery
    where (
      (delivery.status in ('pending', 'failed') and delivery.next_attempt_at <= now())
      or (delivery.status = 'processing' and delivery.processing_started_at < now() - interval '15 minutes')
    )
    order by delivery.occurred_at, delivery.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 20), 100))
  )
  update public.notification_email_deliveries delivery
  set status = 'processing',
      processing_started_at = now(),
      last_error = null
  from claimed
  where delivery.id = claimed.id
  returning delivery.*;
$$;

revoke all on function public.claim_notification_email_deliveries(integer) from public;
revoke all on function public.claim_notification_email_deliveries(integer) from anon;
revoke all on function public.claim_notification_email_deliveries(integer) from authenticated;
grant execute on function public.claim_notification_email_deliveries(integer) to service_role;

create or replace function public.complete_notification_email_delivery(
  p_id bigint,
  p_success boolean,
  p_error text default null,
  p_provider_message_id text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.notification_email_deliveries delivery
  set status = case when p_success then 'sent' else 'failed' end,
      attempt_count = case when p_success then delivery.attempt_count else delivery.attempt_count + 1 end,
      last_error = case when p_success then null else left(coalesce(nullif(btrim(p_error), ''), 'Email delivery failed.'), 2000) end,
      next_attempt_at = case
        when p_success then delivery.next_attempt_at
        when delivery.attempt_count <= 0 then now() + interval '1 minute'
        when delivery.attempt_count = 1 then now() + interval '5 minutes'
        when delivery.attempt_count = 2 then now() + interval '15 minutes'
        else now() + interval '1 hour'
      end,
      processing_started_at = null,
      sent_at = case when p_success then now() else delivery.sent_at end,
      provider_message_id = case when p_success then nullif(btrim(p_provider_message_id), '') else delivery.provider_message_id end
  where delivery.id = p_id
    and delivery.status = 'processing';
end;
$$;

revoke all on function public.complete_notification_email_delivery(bigint, boolean, text, text) from public;
revoke all on function public.complete_notification_email_delivery(bigint, boolean, text, text) from anon;
revoke all on function public.complete_notification_email_delivery(bigint, boolean, text, text) from authenticated;
grant execute on function public.complete_notification_email_delivery(bigint, boolean, text, text) to service_role;

-- DOC Placement first integration. The header does not currently expose a
-- true document Void operation, so only the verified Posted transition is
-- registered. Edit and Void events must be added with their future
-- authoritative business operations.
create or replace function public.set_doc_receiving_posting_metadata()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if lower(btrim(coalesce(new.status, ''))) in ('posted', 'received')
     and lower(btrim(coalesce(old.status, ''))) not in ('posted', 'received') then
    new.posted_at := now();
    new.posted_by := coalesce(new.updated_by, auth.uid(), new.created_by);
    new.posting_version := coalesce(old.posting_version, 0) + 1;
  end if;

  return new;
end;
$$;

drop trigger if exists goods_receipt_set_posting_metadata on public.goods_receipt;
create trigger goods_receipt_set_posting_metadata
before update of status on public.goods_receipt
for each row execute function public.set_doc_receiving_posting_metadata();

create or replace function public.enqueue_doc_receiving_posted_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_fms_type text;
begin
  if lower(btrim(coalesce(new.status, ''))) in ('posted', 'received')
     and lower(btrim(coalesce(old.status, ''))) not in ('posted', 'received') then
    v_fms_type := case lower(btrim(coalesce(new.fms_type, '')))
      when 'broiler' then 'Broiler'
      when 'breeder' then 'Breeder'
      when 'hatchery' then 'Hatchery'
      else null
    end;

    insert into public.notification_outbox (
      module_key,
      event_key,
      entity_type,
      entity_id,
      document_no,
      fms_type,
      farm_id,
      recipient_farm_id,
      actor_auth_id,
      target_url,
      permission_group,
      permission_title,
      title,
      message,
      priority,
      posting_version,
      metadata,
      dedupe_key,
      occurred_at
    ) values (
      'DOC_RECEIVING',
      'DOC_RECEIVING_POSTED',
      'goods_receipt',
      new.id::text,
      new.gr_no,
      v_fms_type,
      new.farm_id,
      new.farm_id,
      coalesce(new.posted_by, new.updated_by, auth.uid(), new.created_by),
      '/inv/doc-receiving/post?id=' || new.id::text,
      'Menus',
      'DOC Placement/view',
      'DOC Placement posted',
      'DOC Placement {document_no} was posted by {initiator_name}.',
      'normal',
      new.posting_version,
      jsonb_build_object(
        'status', 'Posted',
        'farmId', new.farm_id,
        'farmCode', new.farm_code,
        'farmName', new.farm_name,
        'lineCount', (
          select count(*) from public.goods_receipt_doc detail
          where detail.goods_reciept_id = new.id and detail.void = '1'
        ),
        'totalQuantity', (
          select coalesce(sum(detail.quantity_received), 0) from public.goods_receipt_doc detail
          where detail.goods_reciept_id = new.id and detail.void = '1'
        ),
        'actualQuantity', (
          select coalesce(sum(detail.actual_received), 0) from public.goods_receipt_doc detail
          where detail.goods_reciept_id = new.id and detail.void = '1'
        ),
        'doaQuantity', (
          select coalesce(sum(detail.doa_quantity), 0) from public.goods_receipt_doc detail
          where detail.goods_reciept_id = new.id and detail.void = '1'
        ),
        'rejectQuantity', (
          select coalesce(sum(detail.reject_count), 0) from public.goods_receipt_doc detail
          where detail.goods_reciept_id = new.id and detail.void = '1'
        )
      ),
      'DOC_RECEIVING_POSTED:' || new.id::text || ':' || new.posting_version::text,
      coalesce(new.posted_at, now())
    )
    on conflict (dedupe_key) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists goods_receipt_enqueue_posted_event on public.goods_receipt;
create trigger goods_receipt_enqueue_posted_event
after update of status on public.goods_receipt
for each row execute function public.enqueue_doc_receiving_posted_event();

-- Hatchery DOC Dispatch is saved as Draft first. Only this authoritative
-- status transition can stamp posting identity and enqueue the cross-FMS event.
create or replace function public.set_hatchery_doc_dispatch_posting_metadata()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.status = 'Posted' and new.status is distinct from old.status then
    raise exception 'A posted Hatchery DOC Dispatch cannot return to Draft.';
  end if;

  if new.status = 'Posted' and old.status is distinct from 'Posted' then
    if new.destination_farm_id is null or nullif(btrim(new.destination_farm_code), '') is null then
      raise exception 'A destination farm code is required before posting DOC Dispatch.';
    end if;

    if not exists (
      select 1
      from public.farms farm
      where farm.id = new.destination_farm_id
        and farm.code = new.destination_farm_code
        and farm.void = 1
        and farm.approval_status = 'approved'
        and farm.farm_type = 'BR'
    ) then
      raise exception 'The destination must be an active, approved Broiler farm.';
    end if;

    if not exists (
      select 1 from public.dispatch_doc_item item where item.dispatch_doc_id = new.id
    ) then
      raise exception 'At least one DOC Dispatch item is required before posting.';
    end if;

    new.posted_at := now();
    new.posted_by := coalesce(new.posted_by, new.updated_by, auth.uid(), new.created_by);
    new.posting_version := coalesce(old.posting_version, 0) + 1;
  end if;

  return new;
end;
$$;

drop trigger if exists hatchery_doc_dispatch_set_posting_metadata on public.dispatch_doc;
create trigger hatchery_doc_dispatch_set_posting_metadata
before update of status on public.dispatch_doc
for each row execute function public.set_hatchery_doc_dispatch_posting_metadata();

create or replace function public.enqueue_hatchery_doc_dispatch_posted_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'Posted' and old.status is distinct from 'Posted' then
    insert into public.notification_outbox (
      module_key,
      event_key,
      entity_type,
      entity_id,
      document_no,
      fms_type,
      farm_id,
      recipient_farm_id,
      actor_auth_id,
      target_url,
      permission_group,
      permission_title,
      title,
      message,
      priority,
      posting_version,
      metadata,
      dedupe_key,
      occurred_at
    ) values (
      'HATCHERY_DOC_DISPATCH',
      'HATCHERY_DOC_DISPATCH_POSTED',
      'dispatch_doc',
      new.id::text,
      new.dr_no,
      'Hatchery',
      new.destination_farm_id,
      new.destination_farm_id,
      coalesce(new.posted_by, new.updated_by, auth.uid(), new.created_by),
      '/inv/doc-receiving/new?dispatchId=' || new.id::text || '&farmId=' || new.destination_farm_id::text,
      'Menus',
      'DOC Placement/view',
      'Hatchery DOC Dispatch posted',
      'Hatchery DOC Dispatch {document_no} is ready for DOC Receiving.',
      'normal',
      new.posting_version,
      jsonb_build_object(
        'status', 'Posted',
        'destinationFarmId', new.destination_farm_id,
        'destinationFarmCode', new.destination_farm_code,
        'destinationFarmName', new.farm_name,
        'lineCount', (
          select count(*) from public.dispatch_doc_item item
          where item.dispatch_doc_id = new.id
        ),
        'totalQuantity', (
          select coalesce(sum(item.qty), 0) from public.dispatch_doc_item item
          where item.dispatch_doc_id = new.id
        )
      ),
      'HATCHERY_DOC_DISPATCH_POSTED:' || new.id::text || ':' || new.posting_version::text,
      coalesce(new.posted_at, now())
    )
    on conflict (dedupe_key) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists hatchery_doc_dispatch_enqueue_posted_event on public.dispatch_doc;
create trigger hatchery_doc_dispatch_enqueue_posted_event
after update of status on public.dispatch_doc
for each row execute function public.enqueue_hatchery_doc_dispatch_posted_event();

-- Optional Supabase Cron schedule after reviewing pg_cron availability:
-- select cron.schedule(
--   'process-notification-outbox',
--   '* * * * *',
--   $$select public.process_notification_outbox(100);$$
-- );
