create table if not exists public.brd_dr_settings (
  id integer generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  created_by uuid null references auth.users(id),
  updated_at timestamp with time zone null,
  updated_by uuid null references auth.users(id),
  farm_id integer not null,
  farm_code text null,
  farm_name text null,
  batch_auto_selection boolean not null default false,
  void text not null default '1',
  constraint brd_dr_settings_void_check check (void in ('0', '1'))
);

alter table public.brd_dr_settings
  add column if not exists farm_id integer;

alter table public.brd_dr_settings
  add column if not exists farm_code text null;

alter table public.brd_dr_settings
  add column if not exists farm_name text null;

alter table public.brd_dr_settings
  add column if not exists batch_auto_selection boolean not null default false;

alter table public.brd_dr_settings
  drop constraint if exists brd_dr_settings_batch_auto_selection_mode_check;

alter table public.brd_dr_settings
  drop constraint if exists brd_dr_settings_batch_auto_selection_required_check;

alter table public.brd_dr_settings
  drop column if exists batch_auto_selection_mode;

create index if not exists brd_dr_settings_void_idx
  on public.brd_dr_settings (void);

create index if not exists brd_dr_settings_farm_idx
  on public.brd_dr_settings (farm_id);

create unique index if not exists brd_dr_settings_active_farm_uidx
  on public.brd_dr_settings (farm_id)
  where void = '1';
