
\ir ../receiving-sources/fixture.sql

alter table public.farms add column island text;
alter table public.farms add column administrative_region text;
alter table public.recieving add column farm_id bigint references public.farms(id);

create table public.hatch_classification (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  br_no text, classi_ref_no text, farm_id bigint, good_egg numeric, is_active boolean default true
);
create table public.egg_storage_mngt (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), classi_ref_no text, void smallint default 1
);
create table public.egg_pre_warming (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), egg_ref_no text, is_active boolean default true
);
create table public.setter_incubation_process (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), ref_no text, machine_id text, qty_set_egg numeric, void smallint default 1
);
create table public.egg_transfer_process (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), ref_no text, total_egg_transfer numeric, void smallint default 1
);
create table public.egg_hatchery_process (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), egg_ref text, machine_no text, total_egg numeric, void smallint default 1
);
create table public.chick_pullout_process (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), egg_ref_no text, chick_hatch_ref_no text, machine_no text, chicks_hatched numeric, void smallint default 1
);
create table public.chick_grading_process (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), egg_ref_no text, batch_code text,
  class_a numeric, class_b numeric, class_a_junior numeric, class_c numeric,
  cull_chicks numeric, dead_chicks numeric, infertile numeric, dead_germ numeric,
  live_pip numeric, dead_pip numeric, unhatched numeric, rotten numeric, exploder numeric,
  unhatched_good numeric, unhatched_bad numeric, infertile_good numeric, infertile_bad numeric,
  void smallint default 1
);
create table public.disposal (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(), farm_id bigint, batch_code text, void smallint default 1
);
create table public.disposal_item (
  id bigint generated by default as identity primary key, disposal_id bigint, sku text, uom text, qty numeric
);

\ir ../../../../app/sql/new/hatchery_lifecycle_report.sql
