create table if not exists public.doc_rec_settings (
  id integer generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_at timestamp with time zone null,
  updated_by uuid null,
  good_doc integer null references public.items(id),
  bad_doc integer null references public.items(id),
  reject_doc integer null references public.items(id),
  void text not null default '1'
);

alter table public.doc_rec_settings
  add column if not exists reject_doc integer null references public.items(id);

create index if not exists doc_rec_settings_void_idx
  on public.doc_rec_settings (void);

create index if not exists doc_rec_settings_good_doc_idx
  on public.doc_rec_settings (good_doc);

create index if not exists doc_rec_settings_bad_doc_idx
  on public.doc_rec_settings (bad_doc);

create index if not exists doc_rec_settings_reject_doc_idx
  on public.doc_rec_settings (reject_doc);
