begin;

create table if not exists public.brd_cu_settings (
  id integer generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  created_by uuid null references auth.users(id),
  updated_at timestamp with time zone null,
  updated_by uuid null references auth.users(id),
  farm_id integer not null,
  farm_code text null,
  farm_name text null,
  batch_auto_selection boolean not null default true,
  target_cleanup_age integer not null default 0,
  void text not null default '1',
  constraint brd_cu_settings_void_check check (void in ('0', '1')),
  constraint brd_cu_settings_target_cleanup_age_check check (target_cleanup_age >= 0)
);

create index if not exists brd_cu_settings_void_idx on public.brd_cu_settings (void);
create index if not exists brd_cu_settings_farm_idx on public.brd_cu_settings (farm_id);
create unique index if not exists brd_cu_settings_active_farm_uidx
  on public.brd_cu_settings (farm_id) where void = '1';

commit;
