import writeXlsxFile, { type Feature } from 'write-excel-file/browser'
import {
  getOrderOfSiblings,
  insertElementMarkupAccordingToOrderOfSiblings,
  sanitizeTextContent,
} from 'write-excel-file/utility'

import type { ItemUomGroup } from './api'
import {
  getItemGroupPath,
  ITEM_GROUP_MAX_SUBGROUP_LEVELS,
  type ItemGroup,
} from '../itemgroups/api'

type TemplateCell = {
  value: string
  align?: 'left' | 'center'
  alignVertical?: 'center'
  backgroundColor?: string
  borderColor?: string
  borderStyle?: 'thin'
  columnSpan?: number
  fontWeight?: 'bold'
  height?: number
  textColor?: string
  wrap?: boolean
}

const TEMPLATE_HEADERS = [
  'Item Name', 'Description', 'Barcode', 'UoM Group', 'Item Group',
  'Sub Group Level 1', 'Sub Group Level 2', 'Sub Group Level 3',
  'Sub Group Level 4', 'Sub Group Level 5',
  'FMS Group', 'Inventory Item', 'Sales Item', 'Purchase Item', 'Delivery Item',
  'Manage Batch Numbers', 'Manage Serial Numbers', 'Batch Management Method',
  'Shelf Life Days', 'Expiration Months', 'Expiry Required',
  'Allow Negative Batch Stock', 'Batch Number Series', 'Min On Hand', 'Max On Hand',
]

const INSTRUCTIONS = [
  ['Item Name', 'Required', 'Enter the item name. Item Code is generated by Item Master after import.'],
  ['UoM Group', 'Required', 'Choose an active UoM Group. The base UoM is resolved automatically.'],
  ['Item Group', 'Required', 'Choose an active root Item Group.'],
  ['Sub Group Levels 1-5', 'Optional', 'Choose each level from left to right. Each dropdown is filtered by its parent. Stop when a leaf group is reached; unused deeper levels stay blank.'],
  ['FMS Group', 'Required', 'Choose Broiler, Breeder, or Hatchery.'],
  ['Yes/No fields', 'Required', 'Use Yes or No for every item-control field.'],
  ['Batch Management Method', 'Conditional', 'Use MANUAL or AUTO when Manage Batch Numbers is Yes; otherwise use NONE.'],
  ['Shelf Life / Expiration', 'Optional', 'Enter whole numbers greater than or equal to 0. These values apply only to batch-managed items.'],
  ['Min / Max On Hand', 'Optional', 'Enter numbers greater than or equal to 0. Max cannot be less than Min.'],
]

type ItemMasterTemplateOptions = {
  itemGroups: ItemGroup[]
  subItemGroups: ItemGroup[]
  uomGroups: ItemUomGroup[]
}

const uniqueSorted = (values: string[]) => Array.from(new Set(values.map(value => value.trim()).filter(Boolean)))
  .sort((left, right) => left.localeCompare(right))
const listFormula = (column: string, values: string[]) =>
  `'Dropdown Lists'!$${column}$2:$${column}$${Math.max(2, values.length + 1)}`
const formulaElement = (name: 'formula1' | 'formula2', value: string) =>
  `<${name}>${sanitizeTextContent(value)}</${name}>`

const dependentListColumns = [
  { parent: 'F', child: 'G' },
  { parent: 'H', child: 'I' },
  { parent: 'J', child: 'K' },
  { parent: 'L', child: 'M' },
  { parent: 'N', child: 'O' },
] as const

const dependentListFormula = (
  parentCell: string,
  parentColumn: string,
  childColumn: string,
  rowCount: number,
) => {
  const lastRow = Math.max(2, rowCount + 1)
  const parentRange = `'Dropdown Lists'!$${parentColumn}$2:$${parentColumn}$${lastRow}`
  return `OFFSET('Dropdown Lists'!$${childColumn}$2,MATCH(${parentCell},${parentRange},0)-1,0,COUNTIF(${parentRange},${parentCell}),1)`
}

const dataValidationFeature = (
  lists: string[][],
  dependentPairs: Array<Array<[string, string]>>,
): Feature<File | Blob | ArrayBuffer> => ({
  files: {
    transform: {
      'xl/worksheets/sheet{id}.xml': {
        transform: (xml, _sheetOptions, { sheetIndex }) => {
          if (sheetIndex !== 0) return xml

          const validations = [
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid UoM Group" error="Choose a UoM Group from the dropdown list." sqref="D2:D501">${formulaElement('formula1', listFormula('A', lists[0]))}</dataValidation>`,
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid Item Group" error="Choose an Item Group from the dropdown list." sqref="E2:E501">${formulaElement('formula1', listFormula('B', lists[1]))}</dataValidation>`,
            ...dependentListColumns.map((columns, levelIndex) => {
              const itemSheetColumn = String.fromCharCode('F'.charCodeAt(0) + levelIndex)
              const parentSheetColumn = String.fromCharCode(itemSheetColumn.charCodeAt(0) - 1)
              const formula = dependentListFormula(
                `$${parentSheetColumn}2`,
                columns.parent,
                columns.child,
                dependentPairs[levelIndex]?.length ?? 0,
              )
              return `<dataValidation type="list" allowBlank="1" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid Sub Group" error="Choose a Sub Group under the previously selected group or leave this and deeper levels blank." sqref="${itemSheetColumn}2:${itemSheetColumn}501">${formulaElement('formula1', formula)}</dataValidation>`
            }),
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid FMS Group" error="Choose Broiler, Breeder, or Hatchery." sqref="K2:K501">${formulaElement('formula1', listFormula('C', lists[2]))}</dataValidation>`,
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid value" error="Choose Yes or No." sqref="L2:Q501">${formulaElement('formula1', listFormula('D', lists[3]))}</dataValidation>`,
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid method" error="Choose NONE, MANUAL, or AUTO." sqref="R2:R501">${formulaElement('formula1', listFormula('E', lists[4]))}</dataValidation>`,
            `<dataValidation type="list" allowBlank="0" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid value" error="Choose Yes or No." sqref="U2:V501">${formulaElement('formula1', listFormula('D', lists[3]))}</dataValidation>`,
            `<dataValidation type="whole" operator="greaterThanOrEqual" allowBlank="1" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid number" error="Enter a whole number greater than or equal to 0." sqref="S2:T501">${formulaElement('formula1', '0')}</dataValidation>`,
            `<dataValidation type="decimal" operator="greaterThanOrEqual" allowBlank="1" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid quantity" error="Enter a number greater than or equal to 0." sqref="X2:Y501">${formulaElement('formula1', '0')}</dataValidation>`,
          ]
          const markup = `<dataValidations count="${validations.length}">${validations.join('')}</dataValidations>`
          return insertElementMarkupAccordingToOrderOfSiblings(
            xml,
            markup,
            getOrderOfSiblings('xl/worksheets/sheet{id}.xml', 'worksheet') ?? [],
            'worksheet',
          )
        },
      },
    },
  },
})

const thinBorder = { borderColor: '#D6D3D1', borderStyle: 'thin' as const }
const headerCell = (value: string): TemplateCell => ({
  value,
  align: 'center',
  alignVertical: 'center',
  backgroundColor: '#1C1917',
  fontWeight: 'bold',
  textColor: '#FFFFFF',
  wrap: true,
  height: 32,
  ...thinBorder,
})
const instructionHeaderCell = (value: string): TemplateCell => ({
  value,
  backgroundColor: '#E7E5E4',
  fontWeight: 'bold',
  wrap: true,
  ...thinBorder,
})

export function getItemMasterTemplateSheets(options: ItemMasterTemplateOptions) {
  const groupLabel = (group: ItemGroup) => `${group.code} - ${group.name}`
  const itemGroups = options.itemGroups.flatMap(group => group.code ? [`${group.code} - ${group.name}`] : [])
  const uomGroups = options.uomGroups.map(group => `${group.code} - ${group.name}`)
  const dependentPairs = Array.from(
    { length: ITEM_GROUP_MAX_SUBGROUP_LEVELS },
    () => [] as Array<[string, string]>,
  )

  options.itemGroups.forEach(root => {
    if (root.id == null) return
    options.subItemGroups.forEach(group => {
      if (group.id == null) return
      const path = getItemGroupPath(options.subItemGroups, Number(root.id), Number(group.id))
      if (path.length < 1 || path.length > ITEM_GROUP_MAX_SUBGROUP_LEVELS) return
      const parent = path.length === 1 ? root : path[path.length - 2]
      const child = path.at(-1)
      if (!parent || !child) return
      dependentPairs[path.length - 1].push([groupLabel(parent), groupLabel(child)])
    })
  })
  dependentPairs.forEach(pairs => pairs.sort((left, right) =>
    left[0].localeCompare(right[0]) || left[1].localeCompare(right[1]),
  ))

  const lists = [
    uniqueSorted(uomGroups),
    uniqueSorted(itemGroups),
    ['Broiler', 'Breeder', 'Hatchery'],
    ['Yes', 'No'],
    ['NONE', 'MANUAL', 'AUTO'],
  ]
  const listHeaders = [
    'UoM Groups', 'Item Groups', 'FMS Groups', 'Yes / No', 'Batch Methods',
    ...dependentPairs.flatMap((_, levelIndex) => [
      `Level ${levelIndex + 1} Parent`,
      `Sub Group Level ${levelIndex + 1} Options`,
    ]),
  ]
  const dropdownRowCount = Math.max(
    ...lists.map(list => list.length),
    ...dependentPairs.map(pairs => pairs.length),
    1,
  )

  return {
    lists,
    dependentPairs,
    sheets: [
      {
        data: [TEMPLATE_HEADERS.map(headerCell)],
        sheet: 'Items',
        columns: TEMPLATE_HEADERS.map((header, index) => ({
          width: index === 0 || index === 1 ? 28 : Math.max(14, Math.min(header.length + 4, 26)),
        })),
        stickyRowsCount: 1,
        showGridLines: false,
        orientation: 'landscape' as const,
        zoomScale: 0.75,
      },
      {
        data: [
          [{ value: 'Item Master Import Template Instructions', backgroundColor: '#1C1917', columnSpan: 3, fontWeight: 'bold' as const, textColor: '#FFFFFF', height: 30 }],
          [{ value: 'Complete the Items worksheet without changing its column names. Select Sub Group Levels from left to right; each level is optional and filtered by the previously selected group. If a selected group has children, continue until a leaf is reached. Import validates the entire worksheet before asking for confirmation. It creates new Item Master records only; Item Codes are generated from the selected Item Group.', columnSpan: 3, wrap: true, height: 76 }],
          ['Field', 'Requirement', 'Entry rules'].map(instructionHeaderCell),
          ...INSTRUCTIONS.map(row => row.map(value => ({ value, alignVertical: 'center' as const, wrap: true, ...thinBorder }))),
        ],
        sheet: 'Instructions',
        columns: [{ width: 30 }, { width: 16 }, { width: 88 }],
        stickyRowsCount: 3,
        showGridLines: false,
        zoomScale: 0.95,
      },
      {
        data: [
          listHeaders.map(instructionHeaderCell),
          ...Array.from({ length: dropdownRowCount }, (_, index) => [
            ...lists.map(list => list[index] ?? ''),
            ...dependentPairs.flatMap(pairs => [pairs[index]?.[0] ?? '', pairs[index]?.[1] ?? '']),
          ].map(value => ({ value, ...thinBorder }))),
        ],
        sheet: 'Dropdown Lists',
        columns: [
          { width: 30 }, { width: 32 }, { width: 18 }, { width: 14 }, { width: 18 },
          ...dependentPairs.flatMap(() => [{ width: 32 }, { width: 36 }]),
        ],
        stickyRowsCount: 1,
        showGridLines: false,
        zoomScale: 0.9,
      },
    ],
  }
}

export async function exportItemMasterTemplate(options: ItemMasterTemplateOptions) {
  const { lists, dependentPairs, sheets } = getItemMasterTemplateSheets(options)
  await writeXlsxFile(sheets, {
    fontFamily: 'Arial',
    fontSize: 10,
    features: [dataValidationFeature(lists, dependentPairs)],
  }).toFile('item-master-import-template.xlsx')
}
