create table if not exists public.brd_fc_settings (
  id integer generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  created_by uuid null references auth.users(id),
  updated_at timestamp with time zone null,
  updated_by uuid null references auth.users(id),
  farm_id integer not null,
  farm_code text null,
  farm_name text null,
  allow_advance_posting boolean not null default false,
  auto_feed_batch_selection boolean not null default false,
  auto_feed_batch_selection_mode text not null default 'USER_SELECTED',
  auto_mortality_rate_batch_selection boolean not null default false,
  void text not null default '1',
  constraint brd_fc_settings_auto_feed_batch_selection_mode_check
    check (auto_feed_batch_selection_mode in ('USER_SELECTED', 'FIFO')),
  constraint brd_fc_settings_void_check check (void in ('0', '1'))
);

alter table public.brd_fc_settings
  add column if not exists farm_id integer;

alter table public.brd_fc_settings
  add column if not exists farm_code text null;

alter table public.brd_fc_settings
  add column if not exists farm_name text null;

alter table public.brd_fc_settings
  add column if not exists allow_advance_posting boolean not null default false;

alter table public.brd_fc_settings
  add column if not exists auto_feed_batch_selection boolean not null default false;

alter table public.brd_fc_settings
  add column if not exists auto_feed_batch_selection_mode text not null default 'USER_SELECTED';

alter table public.brd_fc_settings
  drop constraint if exists brd_fc_settings_auto_feed_batch_selection_mode_check;

alter table public.brd_fc_settings
  add constraint brd_fc_settings_auto_feed_batch_selection_mode_check
  check (auto_feed_batch_selection_mode in ('USER_SELECTED', 'FIFO'));

alter table public.brd_fc_settings
  add column if not exists auto_mortality_rate_batch_selection boolean not null default false;

create index if not exists brd_fc_settings_void_idx
  on public.brd_fc_settings (void);

create index if not exists brd_fc_settings_farm_idx
  on public.brd_fc_settings (farm_id);

create unique index if not exists brd_fc_settings_active_farm_uidx
  on public.brd_fc_settings (farm_id)
  where void = '1';
