-- Disposable database only. Mirrors the production users column types.
do $$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon; end if; end $$;
do $$ begin if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated; end if; end $$;
do $$ begin if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role bypassrls; end if; end $$;
do $$ begin if not exists(select 1 from pg_roles where rolname='authenticator') then create role authenticator; end if; end $$;
create schema auth;
create schema storage;
create publication supabase_realtime;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql stable as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;
grant usage on schema auth to anon,authenticated,service_role;
create table auth.users(id uuid primary key,email text,raw_app_meta_data jsonb default '{}',banned_until timestamptz);
create table public.users(
 id bigint generated by default as identity primary key,auth_id uuid unique references auth.users(id),email text not null,
 created_at timestamptz default now(),created_by uuid,updated_at timestamp,updated_by uuid,"docStatus" text,
 firstname text,middlename text,lastname text,gender text,phone text,mobile text,birthdate timestamp,
 location text,remarks text,issuper text not null default '0',default_farm text,supervisor bigint,
 isactive text default '0',region text,archipelago text,users_group_id bigint,fms_type text,user_type smallint not null default 3,
 registration_completed_at timestamptz
);
create table farms(id bigint primary key,code text,name text);
create table users_farms(users_id bigint,farm_id bigint,farm_code text,void text);
create table user_permissions(user_id uuid,group_name text,title text,is_visible boolean);
create table business_test(id integer);
insert into business_test values(1);
alter table business_test enable row level security;
create policy existing_access on business_test for all to anon,authenticated using(true) with check(true);
grant all on business_test to anon,authenticated;
alter table users enable row level security;
create policy existing_users on users for all to authenticated using(true) with check(true);
grant all on users to authenticated;
create table storage.objects(id integer);
alter table storage.objects enable row level security;
create policy existing_storage on storage.objects for all to authenticated using(true) with check(true);
