create table if not exists public.users_group (
  id bigint generated by default as identity primary key,
  code text not null,
  group_name text not null,
  void text not null default '1',
  created_at timestamp with time zone not null default now(),
  created_by uuid null references auth.users(id),
  updated_at timestamp with time zone null,
  updated_by uuid null references auth.users(id),
  constraint users_group_code_key unique (code),
  constraint users_group_code_format_check check (code ~ '^UG-[0-9]{6}$'),
  constraint users_group_group_name_check check (length(trim(group_name)) > 0),
  constraint users_group_void_check check (void in ('0', '1'))
);

create index if not exists users_group_void_idx
  on public.users_group (void);

create index if not exists users_group_group_name_idx
  on public.users_group (group_name);
