-- Install as the database owner. Installation does not renumber any data.
-- Preview: select public.offset_broiler_cycles_1000();
-- Apply once: select public.offset_broiler_cycles_1000(true);
-- Run in a fresh transaction during maintenance (clients must refresh afterward).
-- This is an administrative master-data repair, not a document Post/Edit/Void.
-- Existing lifecycle RPCs/events are unchanged; no business notifications or
-- inventory postings are generated by this repair. Historical audit snapshots
-- remain historical; the audit below records the old/new identities.
begin;

create table if not exists public.broiler_cycle_offset_audit (
  operation text primary key check (operation = 'BROILER_CYCLES_PLUS_1000'),
  applied_at timestamptz not null default now(),
  applied_by text not null default current_user,
  result jsonb not null
);
alter table public.broiler_cycle_offset_audit enable row level security;
revoke all on public.broiler_cycle_offset_audit from public, anon, authenticated, service_role;

create or replace function public.offset_broiler_cycles_1000(p_apply boolean default false)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
set lock_timeout = '5s'
as $$
declare
  v_result jsonb;
  v_table text;
  v_column record;
  v_row record;
  v_trigger record;
  v_count bigint;
  v_counts jsonb := '{}'::jsonb;
  v_tables text[] := array[
    'doc_farm_cycles', 'flock_card', 'inventory_postings',
    'flock_card_origin', 'brd_fc_ba', 'brd_fc_line',
    'goods_receipt_items', 'goods_issue_items', 'inventory_transfer_items',
    'item_batches', 'br_delivery_lines', 'br_cleanup_lines',
    'vnm_documents', 'vnm_line_batches'
  ];
begin
  -- Invoker rights plus revoked EXECUTE keep this out of browser/service RPCs.
  -- The caller must own all affected tables to suspend their user triggers.
  if current_user in ('anon', 'authenticated', 'service_role', 'authenticator') then
    raise exception 'Run this maintenance function as the database owner.';
  end if;
  perform pg_advisory_xact_lock(73192, 1000);
  select result into v_result from public.broiler_cycle_offset_audit
  where operation = 'BROILER_CYCLES_PLUS_1000';
  if found then
    return v_result || jsonb_build_object('alreadyApplied', true);
  end if;

  -- Lock before reading mappings; concurrent document writes must not observe
  -- half-renumbered identities. Optional module tables may not be installed.
  foreach v_table in array v_tables loop
    if to_regclass(format('public.%I', v_table)) is not null then
      execute format('lock table public.%I in access exclusive mode', v_table);
    elsif v_table in ('doc_farm_cycles', 'flock_card', 'inventory_postings') then
      raise exception 'Required table public.% is missing.', v_table;
    end if;
  end loop;

  -- Reject unsupported values rather than silently leave existing cycles behind.
  if exists (select 1 from public.flock_card
    where nullif(btrim(cycle_no), '') is not null and btrim(cycle_no) !~ '^[0-9]+$') then
    raise exception 'Non-numeric flock_card cycle numbers must be resolved first.';
  end if;
  if exists (select 1 from public.flock_card
    where nullif(btrim(cycle_no), '') is not null
      and btrim(cycle_no)::numeric not between 1 and 9223372036854774806)
    or exists (select 1 from public.doc_farm_cycles where cycle_no > 9223372036854774806) then
    raise exception 'Cycle numbers must remain positive and leave room for the next bigint cycle.';
  end if;
  if exists (select 1 from public.flock_card c left join public.farms f on f.id = c.farm_id
    where nullif(btrim(c.cycle_no), '') is not null and f.id is null)
    or exists (select 1 from public.doc_farm_cycles c left join public.farms f on f.id = c.farm_id
      where f.id is null) then
    raise exception 'Every numbered cycle must reference a canonical farms.id.';
  end if;
  if exists (select 1 from public.flock_card c
    left join public.doc_farm_cycles f on f.id = c.farm_cycle_id
    where c.farm_cycle_id is not null and
      (f.id is null or f.farm_id is distinct from c.farm_id
        or nullif(btrim(c.cycle_no), '')::numeric is distinct from f.cycle_no::numeric)) then
    raise exception 'A flock card does not match its linked farm cycle. Resolve it before renumbering.';
  end if;

  -- Temp objects are recreated so repeated previews in one transaction work.
  drop table if exists pg_temp.broiler_offset_cards;
  drop table if exists pg_temp.broiler_offset_batches;
  drop table if exists pg_temp.broiler_offset_columns;
  drop table if exists pg_temp.broiler_offset_triggers;
  create temp table broiler_offset_cards on commit drop as
    select id, farm_id, building_whse_id, cycle_no as old_cycle,
      (btrim(cycle_no)::bigint + 1000)::text as new_cycle
    from public.flock_card where nullif(btrim(cycle_no), '') is not null;
  create temp table broiler_offset_batches (
    old_batch text primary key, new_batch text not null unique, old_cycle bigint not null
  ) on commit drop;
  insert into pg_temp.broiler_offset_batches
    select distinct format('DOC:F%s:B%s:%s', farm_id, building_whse_id, btrim(old_cycle)),
      format('DOC:F%s:B%s:%s', farm_id, building_whse_id, new_cycle), btrim(old_cycle)::bigint
    from pg_temp.broiler_offset_cards where building_whse_id is not null;

  -- Fixed, reviewed batch-bearing columns; never accepts arbitrary table input.
  create temp table broiler_offset_columns on commit drop as
    select t.table_name, t.column_name from (values
      ('inventory_postings', 'batch_number'), ('inventory_postings', 'ref'), ('inventory_postings', 'ref2'),
      ('flock_card_origin', 'batch_no'), ('brd_fc_ba', 'batch_no'),
      ('goods_receipt_items', 'batch_number'), ('goods_issue_items', 'batch_number'),
      ('inventory_transfer_items', 'batch_number'), ('item_batches', 'batch_number'),
      ('br_delivery_lines', 'batch_number'), ('br_cleanup_lines', 'batch_number'),
      ('vnm_line_batches', 'batch_number')
    ) t(table_name, column_name)
    join information_schema.columns c on c.table_schema = 'public'
      and c.table_name = t.table_name and c.column_name = t.column_name;

  for v_column in select * from pg_temp.broiler_offset_columns loop
    execute format('select count(*) from public.%I t
      where upper(btrim(t.%I)) like ''DOC:F%%'' and not exists
      (select 1 from pg_temp.broiler_offset_batches m where m.old_batch = upper(btrim(t.%I)))',
      v_column.table_name, v_column.column_name, v_column.column_name) into v_count;
    if v_count > 0 then
      raise exception 'Unmapped DOC batch references in %.%; resolve them before renumbering.',
        v_column.table_name, v_column.column_name;
    end if;
    execute format('select count(*) from public.%I t join pg_temp.broiler_offset_batches m
      on m.old_batch = upper(btrim(t.%I))', v_column.table_name, v_column.column_name) into v_count;
    v_counts := v_counts || jsonb_build_object(v_column.table_name || '.' || v_column.column_name, v_count);
  end loop;

  if to_regclass('public.brd_fc_line') is not null then
    if exists (select 1 from public.brd_fc_line
      where extra ? 'mortalityBatchAllocations'
        and jsonb_typeof(extra->'mortalityBatchAllocations') <> 'array') then
      raise exception 'Invalid mortality batch allocation JSON.';
    end if;
    if exists (select 1 from public.brd_fc_line l
      cross join lateral jsonb_array_elements(l.extra->'mortalityBatchAllocations') a
      where upper(btrim(a->>'batchNumber')) like 'DOC:F%'
        and not exists (select 1 from pg_temp.broiler_offset_batches m
          where m.old_batch = upper(btrim(a->>'batchNumber')))) then
      raise exception 'Unmapped mortality allocation DOC batch.';
    end if;
  end if;
  if to_regclass('public.vnm_documents') is not null then
    if exists (select 1 from public.vnm_documents d
      left join public.doc_farm_cycles c on c.id = d.farm_cycle_id
      where d.fms_type = 'Broiler' and (d.cycle_no is not null or d.farm_cycle_id is not null)
        and (c.id is null or c.farm_id is distinct from d.farm_id or c.cycle_no is distinct from d.cycle_no)) then
      raise exception 'A Broiler medication document does not match its farm cycle.';
    end if;
  end if;

  v_result := jsonb_build_object('applied', false, 'offset', 1000,
    'farmCycles', (select count(*) from public.doc_farm_cycles),
    'flockCards', (select count(*) from pg_temp.broiler_offset_cards),
    'blankCycleCardsUnchanged', (select count(*) from public.flock_card where nullif(btrim(cycle_no), '') is null),
    'batchReferences', v_counts,
    'farmCycleMap', coalesce((select jsonb_agg(jsonb_build_object(
      'id', id, 'farmId', farm_id, 'old', cycle_no, 'new', cycle_no + 1000)) from public.doc_farm_cycles), '[]'::jsonb),
    'flockCardMap', coalesce((select jsonb_agg(to_jsonb(m)) from pg_temp.broiler_offset_cards m), '[]'::jsonb));
  if not coalesce(p_apply, false) then return v_result; end if;
  if not exists (select 1 from public.doc_farm_cycles)
    and not exists (select 1 from pg_temp.broiler_offset_cards) then return v_result; end if;

  -- Renaming origins/allocations must not repost inventory or run active-only
  -- placement checks against historical cycles. Suspend USER triggers only,
  -- under exclusive locks, and restore each original mode. FK/check/unique
  -- constraints remain enabled. Any exception rolls all DDL and DML back.
  create temp table broiler_offset_triggers on commit drop as
    select c.relname as table_name, t.tgname, t.tgenabled
    from pg_trigger t join pg_class c on c.oid = t.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = any(v_tables)
      and not t.tgisinternal and t.tgenabled <> 'D';
  for v_trigger in select * from pg_temp.broiler_offset_triggers loop
    execute format('alter table public.%I disable trigger %I', v_trigger.table_name, v_trigger.tgname);
  end loop;

  -- Descending order handles existing 1 and 1001 without unique-key collisions
  -- or accidentally shifting a newly renamed value twice.
  for v_row in select id from public.doc_farm_cycles order by cycle_no desc loop
    update public.doc_farm_cycles set cycle_no = cycle_no + 1000 where id = v_row.id;
  end loop;
  for v_row in select * from pg_temp.broiler_offset_cards order by old_cycle::bigint desc loop
    update public.flock_card set cycle_no = v_row.new_cycle where id = v_row.id;
  end loop;
  if to_regclass('public.vnm_documents') is not null then
    update public.vnm_documents d set cycle_no = c.cycle_no
    from public.doc_farm_cycles c where d.fms_type = 'Broiler' and d.farm_cycle_id = c.id;
  end if;

  if to_regclass('public.brd_fc_line') is not null then
    update public.brd_fc_line l set extra = jsonb_set(l.extra, '{mortalityBatchAllocations}', (
      select jsonb_agg(case when m.new_batch is null then a.value
        else jsonb_set(a.value, '{batchNumber}', to_jsonb(m.new_batch)) end order by a.ordinality)
      from jsonb_array_elements(l.extra->'mortalityBatchAllocations') with ordinality a
      left join pg_temp.broiler_offset_batches m on m.old_batch = upper(btrim(a.value->>'batchNumber'))
    )) where exists (
      select 1 from jsonb_array_elements(l.extra->'mortalityBatchAllocations') a
      join pg_temp.broiler_offset_batches m on m.old_batch = upper(btrim(a->>'batchNumber'))
    );
  end if;
  for v_row in select * from pg_temp.broiler_offset_batches order by old_cycle desc loop
    for v_column in select * from pg_temp.broiler_offset_columns loop
      execute format('update public.%I set %I = $1 where upper(btrim(%I)) = $2',
        v_column.table_name, v_column.column_name, v_column.column_name)
      using v_row.new_batch, v_row.old_batch;
    end loop;
  end loop;

  for v_trigger in select * from pg_temp.broiler_offset_triggers loop
    execute format('alter table public.%I enable %s trigger %I', v_trigger.table_name,
      case v_trigger.tgenabled when 'A' then 'always' when 'R' then 'replica' else '' end, v_trigger.tgname);
  end loop;
  v_result := v_result || jsonb_build_object('applied', true);
  insert into public.broiler_cycle_offset_audit(operation, result)
    values ('BROILER_CYCLES_PLUS_1000', v_result);
  return v_result;
end;
$$;
revoke all on function public.offset_broiler_cycles_1000(boolean) from public, anon, authenticated, service_role;
commit;
