-- Additive Workspace task workflow schema.
-- Apply before using My Work or the project Kanban board.

create table if not exists public.workspace_task_statuses (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  color text not null default '#64748b',
  sort_order integer not null default 0,
  is_final boolean not null default false,
  void integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz null,
  constraint workspace_task_statuses_code_key unique (code),
  constraint workspace_task_statuses_code_check check (code ~ '^[A-Z0-9_]+$'),
  constraint workspace_task_statuses_name_check check (length(btrim(name)) between 1 and 80),
  constraint workspace_task_statuses_color_check check (color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint workspace_task_statuses_sort_order_check check (sort_order >= 0),
  constraint workspace_task_statuses_void_check check (void in (0, 1))
);

drop index if exists public.workspace_task_statuses_active_order_key;
create index if not exists workspace_task_statuses_active_order_idx
  on public.workspace_task_statuses (sort_order)
  where void = 1;

insert into public.workspace_task_statuses (code, name, color, sort_order, is_final)
values
  ('TODO', 'To Do', '#64748b', 10, false),
  ('IN_PROGRESS', 'In Progress', '#2563eb', 20, false),
  ('BLOCKED', 'Blocked', '#dc2626', 30, false),
  ('FOR_REVIEW', 'For Review', '#d97706', 40, false),
  ('DONE', 'Done', '#16a34a', 50, true)
on conflict (code) do nothing;

alter table public.tasks
  add column if not exists status_id bigint null;

update public.tasks task_row
set status_id = default_status.id
from (
  select id
  from public.workspace_task_statuses
  where void = 1
  order by sort_order, id
  limit 1
) default_status
where task_row.status_id is null;

alter table public.tasks
  drop constraint if exists tasks_status_id_fkey;

alter table public.tasks
  add constraint tasks_status_id_fkey
  foreign key (status_id)
  references public.workspace_task_statuses(id)
  on update restrict
  on delete restrict;

alter table public.tasks
  alter column status_id set not null;

create index if not exists tasks_status_id_idx on public.tasks(status_id);
create index if not exists tasks_assigned_status_idx on public.tasks(assigned_to, status_id);
create index if not exists tasks_project_status_idx on public.tasks(project_id, status_id);

create or replace function public.workspace_set_default_task_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status_id is null then
    select status_row.id
    into new.status_id
    from public.workspace_task_statuses status_row
    where status_row.void = 1
    order by status_row.sort_order, status_row.id
    limit 1;
  end if;

  if new.status_id is null then
    raise exception 'At least one active Workspace task status is required.';
  end if;

  return new;
end;
$$;

drop trigger if exists tasks_set_default_workspace_status on public.tasks;
create trigger tasks_set_default_workspace_status
before insert on public.tasks
for each row execute function public.workspace_set_default_task_status();

create or replace function public.workspace_protect_task_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.void = 1 and new.void = 0
     and exists (select 1 from public.tasks where status_id = new.id) then
    raise exception 'A task status assigned to existing tasks cannot be deactivated.';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists workspace_task_statuses_protect on public.workspace_task_statuses;
create trigger workspace_task_statuses_protect
before update on public.workspace_task_statuses
for each row execute function public.workspace_protect_task_status();

alter table public.workspace_task_statuses enable row level security;

drop policy if exists workspace_task_statuses_select on public.workspace_task_statuses;
create policy workspace_task_statuses_select
on public.workspace_task_statuses for select
to authenticated
using (true);

drop policy if exists workspace_task_statuses_manage on public.workspace_task_statuses;
create policy workspace_task_statuses_manage
on public.workspace_task_statuses for all
to authenticated
using (
  exists (
    select 1 from public.users app_user
    where app_user.auth_id = auth.uid() and app_user.user_type = 1
  )
  or exists (
    select 1 from public.user_permissions permission_row
    where permission_row.user_id = auth.uid()
      and permission_row.ilink = '/wks/settings/task-workflow/edit'
      and permission_row.is_visible = true
  )
)
with check (
  exists (
    select 1 from public.users app_user
    where app_user.auth_id = auth.uid() and app_user.user_type = 1
  )
  or exists (
    select 1 from public.user_permissions permission_row
    where permission_row.user_id = auth.uid()
      and permission_row.ilink = '/wks/settings/task-workflow/edit'
      and permission_row.is_visible = true
  )
);

grant select, insert, update on public.workspace_task_statuses to authenticated;
grant usage, select on sequence public.workspace_task_statuses_id_seq to authenticated;

notify pgrst, 'reload schema';
